### ISSUE TITLE
Updates to Server Calls

### ISSUE THREAD

**Issue by SeanMarcoux** [SOEN341/Schedule-Builder#56]
/addcourse: Since courseID is a unique identifier, it is left to the server side to determine it. However, courseID is still needed on the client side, so addcourse should  return {success:'true', courseID:'2'}
I imagine success would be false if there is already a course with that course code in that semester registered on the DB

**Comment by SeanMarcoux** [comment]
Same applies to /addsection, actually. I need it to return the same thing

**Comment by SeanMarcoux** [comment]
I would also like to know if /editcourse or /editsection will return anything. I think they should also be returning {success:'true'} based on if the information conflicts with other courses/sections

**Comment by Cavonte** [comment]
I am not so sure anymore the way it works is when we make the server call we out the value of courseid and section id to null so that the server increments them. Not sure how I would return them.
That could be done with another select query I guess.

As for the edit section/course,  I will fix them. Initially I assumed the user would know in advance what section he is modifying.

**Comment by Cavonte** [comment]
Okay I updated the server calls. You can see the outputs in the server calls document. I think you can close this issue unless you notice anything else that need to be done.

**Comment by Cavonte** [comment]
I think we can close this right ?
